### ISSUE TITLE
Stormy weather disabling all monitors except main radar

### ISSUE THREAD

**Issue by LoneMekkAzulf40K** [Zaggy1024/LC_OpenBodyCams#42] opened 2024-05-20 12:13 UTC
Hello !
Many times now during our playthroughs, we had this annoying bug that when the ship get struck by lightning, monitors go off and only the middle screen can go on again.
The only solution we have now is to quit and re-host or relaunch the game entirely.
General Improvements resolved this bug not too long ago, but we noticed this bug only happens again when we buy the BodyCam ship upgrade, which is why i am posting here, thinking it may come from OpenBodyCam maybe ?

Here is the code of our modpack, in case it's just a conflict of something else we didn't notice at the time :
018f92dc-f8e8-7cc7-dfb0-f73dcf34b329

To reproduce the bug, you just need to buy the bodycam ship upgrade and then go on Stormy and get struck by lightning on the ship.

**Comment by Zaggy1024** [comment] 2024-05-20 22:20
I can't reproduce that with your code, but I'm guessing whatever you're encountering may be an issue with GeneralImprovements, unless some error from OpenBodyCams shows up in your logs when that happens. OpenBodyCams itself doesn't really change anything with the GeneralImprovements BetterMonitors except for the one that it replaces.

It would probably be good to make a copy of your logs when that happens and send it over to Shaosil. If you do find that it's caused by OpenBodyCams, feel free to post here and I can reopen this, but I'll close it for now.

**Closed by Zaggy1024** 2024-05-20 22:20 UTC
