### ISSUE TITLE
1.0.19 problems

### ISSUE THREAD

**Issue by Foxyr1s** [Zaggy1024/LC_OpenBodyCams#11] opened 2024-01-28 10:48 UTC
settings in config
"Framerate" no longer works

"MonitorEmissiveColor" Only works with integers and is terrible at it

**Comment by Zaggy1024** [comment] 2024-01-28 11:03
> settings in config "Framerate" no longer works

I can't reproduce this issue.

> "MonitorEmissiveColor" Only works with integers and is terrible at it

None of the default color component values are integers, and it the color appears correct for me, so you'll have to be clearer about what is "terrible" about it.

These should be two separate issues.

**Comment by Foxyr1s** [comment] 2024-01-28 13:16
I set the maximum framerate to 1. but it looks like 60 or higher

The screen simply does not have a color filter if the value is less than integers

https://youtu.be/azldcRag2Ac

**Comment by Zaggy1024** [comment] 2024-01-28 13:51
I got another report of the issue with the colors and figured out it was the locale changing how the numbers were being parsed. That issue should now be fixed, so I'll close this issue as completed.

Could you test the framerate limit on 1.0.20 and see if it is still occurring, and if so open a new issue? When I set that value to 1, it does indeed limit the framerate as I expect.

**Closed by Zaggy1024** 2024-01-28 13:51 UTC
